version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app/heritage_graph
    environment:
      - ALLOWED_HOSTS=0.0.0.0,localhost,127.0.0.1
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend