# Generated by Django 5.1.3 on 2024-11-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='heritage_data.submission'),
        ),
    ]
