# Generated by Django 5.1.3 on 2025-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contribution_type',
            field=models.CharField(max_length=100),
        ),
    ]
