# Generated by Django 5.1.3 on 2025-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.CharField(blank=True, editable=False, max_length=11, unique=True),
        ),
    ]
