# Generated by Django 5.1.3 on 2024-11-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0004_alter_moderation_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
