# Generated by Django 5.1.3 on 2024-11-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0006_alter_moderation_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('reviewe', 'Review')], default='pending', max_length=10),
        ),
    ]
