# Generated by Django 5.1.3 on 2024-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0013_userprofile_birth_date_userprofile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
